#database properties
spring.datasource.url=jdbc:postgresql://postgres-db:5432/API_BINNACLE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=BINNACLE_USER
spring.datasource.password=PASSWORD
