spring.application.name=pokemon-soap-api
server.port=8080

spring.cloud.openfeign.client.config.pokeapi-client.url=https://pokeapi.co/api/v2
spring.cloud.openfeign.client.config.pokeapi-client.read-timeout=15000
spring.cloud.openfeign.client.config.pokeapi-client.connect-timeout=15000

# logging pattern
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

# logging levels
logging.level.root=INFO
logging.level.com.bankaya.excercise=DEBUG

# log file configuration
logging.file.path=logs
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30