CREATE USER BINNACLE_USER WITH PASSWORD 'PASSWORD';

CREATE DATABASE API_BINNACLE;

GRANT ALL PRIVILEGES ON DATABASE API_BINNACLE TO BINNACLE_USER;

\connect API_BINNACLE;

CREATE TABLE IF NOT EXISTS POKE_API_BINNACLE(
    ID SERIAL PRIMARY KEY,
    ORIGIN_IP VARCHAR(20) not null,
    REQUEST_DATE DATE NOT NULL,
    EXECUTED_METHOD VARCHAR(20) not null,
    DURATION_TIME NUMERIC(10) not null,
    REQUEST TEXT NOT NULL,
    RESPONSE TEXT NOT NULL
);

GRANT INSERT ON POKE_API_BINNACLE TO BINNACLE_USER;